import json
import unittest
from pathlib import Path


class TestNotebookArtifact(unittest.TestCase):
    def test_training_notebook_exists_and_uses_project_modules(self):
        notebook_path = Path("notebooks/01_train_source_binary_segmentation.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))
        self.assertIn("ore_detection.data.color_mask", sources)
        self.assertIn("ore_detection.training.source_dataset", sources)
        self.assertIn("source_binary_downsample", sources)
        self.assertIn("source_binary_gpu_training", sources)
        self.assertIn("data_work' / 'binary_masks", sources)
        self.assertIn("data_work' / 'source_binary_downsampled", sources)
        self.assertIn("models' / 'source_binary_segmentation", sources)
        self.assertIn("MODEL_SERIAL = '001'", sources)
        self.assertIn("models' / 'source_binary_segmentation' / MODEL_SERIAL", sources)
        self.assertIn("masks_colored", sources)
        self.assertNotIn("/masks/", sources)
        self.assertIn("RUN_TRAINING = False", sources)
        self.assertNotIn("RUN_TRAINING = True", sources)
        self.assertIn("from tqdm.auto import tqdm", sources)
        self.assertIn("with tqdm(range(1, EPOCHS + 1), desc='Training') as pbar", sources)
        self.assertIn("pbar.set_postfix(postfix)", sources)
        self.assertNotIn("progress = tqdm(", sources)
        self.assertNotIn("for batch in progress", sources)
        self.assertNotIn("print(row)", sources)
        self.assertIn("EVAL_EVERY_N_EPOCHS = 1", sources)
        self.assertIn("USE_GPU_CACHE = True", sources)
        self.assertIn("USE_GPU_AUGMENTATION = True", sources)
        self.assertIn("PIN_MEMORY = True", sources)
        self.assertIn("non_blocking=True", sources)
        self.assertIn("prepare_downsampled_source_binary_dataset", sources)
        self.assertIn("list_downsampled_source_binary_samples", sources)
        self.assertIn("load_cached_binary_tensors", sources)
        self.assertIn("augment_source_binary_batch", sources)
        self.assertIn("normalize_binary_images", sources)
        self.assertIn("SOURCE_BINARY_TRAIN_RGB_MEAN", sources)
        self.assertIn("BCEWithLogitsLoss", sources)
        self.assertIn("test_metrics['loss'] < best_test_loss", sources)
        self.assertIn("MODELS_ROOT / 'best.pt'", sources)
        self.assertIn("MODELS_ROOT / 'last.pt'", sources)
        self.assertIn("history.json", sources)
        self.assertIn("def plot_training_history(history)", sources)
        self.assertIn("('loss', 'total loss')", sources)
        self.assertIn("('bce_loss', 'binary cross entropy loss')", sources)
        self.assertIn("('dice_loss', 'dice loss')", sources)
        self.assertIn("plot_training_history(history)", sources)

    def test_ore_type_training_notebook_uses_saved_multiclass_masks(self):
        notebook_path = Path("notebooks/02_train_source_ore_segmentation.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))

        self.assertIn("ore_detection.data.ore_type_legend", sources)
        self.assertIn("ore_detection.training.source_ore_dataset", sources)
        self.assertIn("data_work' / 'source_ore_type_masks", sources)
        self.assertIn("source_ore_downsample", sources)
        self.assertIn("source_ore_gpu_training", sources)
        self.assertIn("data_work' / 'source_ore_downsampled", sources)
        self.assertIn("models' / 'source_ore_segmentation", sources)
        self.assertIn("MODEL_SERIAL = '001'", sources)
        self.assertIn("models' / 'source_ore_segmentation' / MODEL_SERIAL", sources)
        self.assertIn("RUN_TRAINING = False", sources)
        self.assertNotIn("RUN_TRAINING = True", sources)
        self.assertIn("from tqdm.auto import tqdm", sources)
        self.assertIn("with tqdm(range(1, EPOCHS + 1), desc='Training') as pbar", sources)
        self.assertIn("pbar.set_postfix(postfix)", sources)
        self.assertNotIn("progress = tqdm(", sources)
        self.assertNotIn("for batch in progress", sources)
        self.assertNotIn("print(row)", sources)
        self.assertIn("EVAL_EVERY_N_EPOCHS = 1", sources)
        self.assertIn("USE_GPU_CACHE = True", sources)
        self.assertIn("USE_GPU_AUGMENTATION = True", sources)
        self.assertIn("PIN_MEMORY = True", sources)
        self.assertIn("non_blocking=True", sources)
        self.assertIn("prepare_downsampled_source_ore_dataset", sources)
        self.assertIn("list_downsampled_source_ore_samples", sources)
        self.assertIn("load_cached_tensors", sources)
        self.assertIn("augment_source_ore_batch", sources)
        self.assertIn("normalize_images", sources)
        self.assertIn("SOURCE_ORE_TRAIN_RGB_MEAN", sources)
        self.assertIn("CrossEntropyLoss", sources)
        self.assertIn("argmax(dim=1)", sources)
        self.assertIn("test_metrics['loss'] < best_test_loss", sources)
        self.assertIn("MODELS_ROOT / 'best.pt'", sources)
        self.assertIn("MODELS_ROOT / 'last.pt'", sources)
        self.assertIn("history.json", sources)
        self.assertIn("def plot_training_history(history)", sources)
        self.assertIn("plt.subplots(len(metric_specs), 1", sources)
        self.assertIn("('loss', 'total loss')", sources)
        self.assertIn("('ce_loss', 'cross entropy loss')", sources)
        self.assertIn("('dice_loss', 'dice loss')", sources)
        self.assertIn("plot_training_history(history)", sources)

    def test_talc_hsv_notebook_uses_project_hsv_module(self):
        notebook_path = Path("notebooks/03_create_talc_hsv_candidates.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))

        self.assertIn("ore_detection.talc.hsv_candidates", sources)
        self.assertIn("DEFAULT_RGB_SUM_THRESHOLD", sources)
        self.assertIn("DEFAULT_EROSION_KERNEL_SIZE", sources)
        self.assertIn("DEFAULT_EROSION_ITERATIONS", sources)
        self.assertIn("DEFAULT_STANDARDIZE_CLIP_SIGMA", sources)
        self.assertIn("DEFAULT_STANDARDIZE_OUTPUT_STD", sources)
        self.assertIn("DEFAULT_STATS_MAX_IMAGE_SIZE", sources)
        self.assertIn("calculate_rgb_mean_std", sources)
        self.assertIn("erode_binary_mask", sources)
        self.assertIn("iter_baseline_crop_paths(BASELINE_ROOT)", sources)
        self.assertIn("rgb_sum_threshold_mask", sources)
        self.assertIn("standardize_image_to_uint8", sources)
        self.assertIn("RGB_SUM_THRESHOLD = DEFAULT_RGB_SUM_THRESHOLD", sources)
        self.assertIn("EROSION_KERNEL_SIZE = DEFAULT_EROSION_KERNEL_SIZE", sources)
        self.assertIn("EROSION_ITERATIONS = DEFAULT_EROSION_ITERATIONS", sources)
        self.assertIn("STATS_MAX_IMAGE_SIZE = DEFAULT_STATS_MAX_IMAGE_SIZE", sources)
        self.assertIn("STANDARDIZE_OUTPUT_STD = DEFAULT_STANDARDIZE_OUTPUT_STD", sources)
        self.assertIn("None means no z-score clipping", sources)
        self.assertIn("raw_mask = rgb_sum_threshold_mask(normalized_image, threshold=RGB_SUM_THRESHOLD)", sources)
        self.assertIn("filtered_mask = erode_binary_mask(", sources)
        self.assertIn("output_std=STANDARDIZE_OUTPUT_STD", sources)
        self.assertIn("'rgb_sum_threshold'", sources)
        self.assertIn("'erosion_kernel_size'", sources)
        self.assertIn("'erosion_iterations'", sources)
        self.assertIn("'stats_max_image_size'", sources)
        self.assertIn("'standardize_output_std'", sources)
        self.assertIn("plt.subplots(1, 3", sources)
        self.assertIn("raw image", sources)
        self.assertIn("after preprocessing (normalization)", sources)
        self.assertIn("RGB-sum mask after erosion", sources)
        self.assertIn("REVIEW_ALL_IMAGES = False", sources)
        self.assertIn("Set REVIEW_ALL_IMAGES = True", sources)
        self.assertNotIn("candidate_area_fraction", sources)
        self.assertNotIn("mask_iou", sources)
        self.assertNotIn("talc_statistic_quantile_rows", sources)
        self.assertNotIn("VALUE_MIN_THRESHOLD", sources)
        self.assertNotIn("HSV_SV_SUM_THRESHOLD", sources)
        self.assertNotIn("HSV_SV_PRODUCT_THRESHOLD", sources)
        self.assertNotIn("hsv_mask_fraction", sources)
        self.assertNotIn("rgb_sum_mask_fraction", sources)
        self.assertNotIn("hsv_rgb_iou", sources)
        self.assertNotIn("ROC-AUC", sources)
        self.assertNotIn("balanced accuracy", sources)

    def test_prediction_descriptor_notebook_uses_trained_models_without_talc_detection(self):
        notebook_path = Path("notebooks/04_predict_ore_masks_and_descriptors.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))

        self.assertIn("inventory_baseline_images", sources)
        self.assertIn("ore_detection.inference.model_prediction", sources)
        self.assertIn("load_simple_unet_checkpoint", sources)
        self.assertIn("save_segmentation_prediction", sources)
        self.assertIn("summarize_prediction_artifacts", sources)
        self.assertIn("write_descriptor_csv", sources)
        self.assertIn("BINARY_MODEL_SERIAL = '001'", sources)
        self.assertIn("ORE_MODEL_SERIAL = '001'", sources)
        self.assertIn("models' / 'source_binary_segmentation' / BINARY_MODEL_SERIAL / 'best.pt'", sources)
        self.assertIn("models' / 'source_ore_segmentation' / ORE_MODEL_SERIAL / 'best.pt'", sources)
        self.assertIn("RUN_PREDICTION = False", sources)
        self.assertIn("SAMPLE_LIMIT = None", sources)
        self.assertIn("records_to_predict = baseline_records if SAMPLE_LIMIT is None", sources)
        self.assertIn("prediction input crop count", sources)
        self.assertIn("panoramas skipped", sources)
        self.assertIn("BINARY_THRESHOLD = 0.5", sources)
        self.assertIn("Talc prediction is disabled", sources)
        self.assertIn("clipped mineral mask", sources)
        self.assertNotIn("ore_detection.talc", sources)
        self.assertNotIn("rgb_sum_threshold_mask", sources)
        self.assertNotIn("HSV", sources)

    def test_intergrowth_calibration_notebook_uses_morphology_classifier(self):
        notebook_path = Path("notebooks/05_calibrate_intergrowth_hard_normal.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))

        self.assertIn("IntergrowthClassifierConfig", sources)
        self.assertIn("choose_hard_threshold", sources)
        self.assertIn("save_intergrowth_classifier_config", sources)
        self.assertIn("RUN_CALIBRATION = False", sources)
        self.assertIn("WINDOW_SIZE = 128", sources)
        self.assertIn("STRIDE = 64", sources)
        self.assertIn("prediction_dirs_by_image_path", sources)
        self.assertIn("metadata.get('image_path')", sources)
        self.assertIn("panoramas", sources)
        self.assertIn("SAMPLE_LIMIT=None", sources)
        self.assertIn("Visual Review", sources)
        self.assertIn("class_index_to_color_image", sources)
        self.assertIn("mineral mask", sources)
        self.assertIn("hard ore score", sources)
        self.assertIn("normal ore score", sources)
        self.assertIn("models' / 'intergrowth_classifier' / '001' / 'classifier.json'", sources)
        self.assertIn("Talc contained", sources)
        self.assertNotIn("rgb_sum_threshold_mask", sources)
        self.assertNotIn("ore_detection.talc", sources)

    def test_erosion_ratio_calibration_notebook_uses_metric_only(self):
        notebook_path = Path("notebooks/06_calibrate_erosion_ratio_intergrowth_metric.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))

        self.assertIn("ErosionRatioConfig", sources)
        self.assertIn("classify_erosion_ratio_intergrowth", sources)
        self.assertIn("choose_erosion_ratio_threshold", sources)
        self.assertIn("save_erosion_ratio_config", sources)
        self.assertIn("RUN_CALIBRATION =", sources)
        self.assertIn("EROSION_KERNEL_SIZE = 5", sources)
        self.assertIn("EROSION_ITERATIONS =", sources)
        self.assertIn("WINDOW_SIZE = 128", sources)
        self.assertIn("MIN_ORE_FRACTION = 0.05", sources)
        self.assertIn("prediction_dirs_by_image_path", sources)
        self.assertIn("metadata.get('image_path')", sources)
        self.assertIn("panoramas", sources)
        self.assertIn("SAMPLE_LIMIT=None", sources)
        self.assertIn("metric is 0", sources.lower())
        self.assertIn("sum(area(eroded class_i mask))", sources)
        self.assertIn("ore_multiclass_mask.png", sources)
        self.assertIn("multiclass_mask=multiclass", sources)
        self.assertIn("multiclass_mask=multiclass_for_score", sources)
        self.assertIn("mineral mask", sources)
        self.assertIn("hard ore score", sources)
        self.assertIn("normal ore score", sources)
        self.assertNotIn("IntergrowthClassifierConfig", sources)
        self.assertNotIn("rgb_sum_threshold_mask", sources)
        self.assertNotIn("ore_detection.talc", sources)

    def test_ore_model_erosion_ratio_notebook_uses_multiclass_model_masks(self):
        notebook_path = Path("notebooks/07_calibrate_erosion_ratio_intergrowth_metric_from_ore_model.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))

        self.assertIn("ErosionRatioConfig", sources)
        self.assertIn("choose_erosion_ratio_threshold", sources)
        self.assertIn("classify_erosion_ratio_intergrowth", sources)
        self.assertIn("save_erosion_ratio_config", sources)
        self.assertIn("load_simple_unet_checkpoint", sources)
        self.assertIn("predict_multiclass_segmentation_image", sources)
        self.assertIn("binary_mask_from_class_image", sources)
        self.assertIn("ORE_MODEL_SERIAL = '001'", sources)
        self.assertIn("models' / 'source_ore_segmentation' / ORE_MODEL_SERIAL / 'best.pt'", sources)
        self.assertIn("intergrowth_erosion_ratio_ore_segmentation", sources)
        self.assertIn("RUN_CALIBRATION = False", sources)
        self.assertIn("SAVE_CALIBRATED_CONFIG = False", sources)
        self.assertIn("SAMPLE_LIMIT = None", sources)
        self.assertIn("ore_mask = binary_mask_from_class_image", sources)
        self.assertIn("multiclass_mask=mineral_mask", sources)
        self.assertIn("ore-model mineral mask", sources)
        self.assertIn("no saved binary segmentation mask is loaded", sources.lower())
        self.assertNotIn("source_binary_segmentation", sources)
        self.assertNotIn("PREDICTION_ROOT", sources)
        self.assertNotIn("prediction_dirs_by_image_path", sources)
        self.assertNotIn("ore_detection.talc", sources)

    def test_ctunet_binary_finetune_notebook_uses_active_learning_masks(self):
        notebook_path = Path("notebooks/08_finetune_binary_segmentation_ctunet_active_learning.ipynb")
        self.assertTrue(notebook_path.exists())
        data = json.loads(notebook_path.read_text(encoding="utf-8"))
        sources = "\n".join("".join(cell.get("source", [])) for cell in data.get("cells", []))

        self.assertIn("create_ct_unet", sources)
        self.assertIn("list_downsampled_source_binary_samples", sources)
        self.assertIn("list_active_learning_binary_samples", sources)
        self.assertIn("load_active_learning_binary_tensors", sources)
        self.assertIn("data_work' / 'source_binary_downsampled", sources)
        self.assertIn("data_work' / 'active_learning_masks", sources)
        self.assertIn("models' / 'source_binary_segmentation' / '001' / 'best.pt'", sources)
        self.assertIn("MODEL_FAMILY = 'source_binary_segmentation_ct_unet'", sources)
        self.assertIn("RUN_TRAINING = False", sources)
        self.assertNotIn("RUN_TRAINING = True", sources)
        self.assertIn("LEARNING_RATE = 1e-4", sources)
        self.assertIn("'out_channels': TARGET_CLASS_COUNT", sources)
        self.assertIn("'class_names': tuple(TARGET_CLASS_NAMES)", sources)
        self.assertIn("'background_index': TARGET_BACKGROUND_INDEX", sources)
        self.assertIn("'architecture': 'ct_unet'", sources)
        self.assertIn("'model_kwargs': dict(CTUNET_MODEL_KWARGS)", sources)
        self.assertIn("def safe_torch_save", sources)
        self.assertIn("safe_torch_save(payload, MODELS_ROOT / 'last.pt')", sources)
        self.assertIn("safe_torch_save(payload, MODELS_ROOT / 'best.pt')", sources)
        self.assertIn("fallback_path", sources)
        self.assertNotIn("torch.save(payload, MODELS_ROOT / 'last.pt')", sources)
        self.assertNotIn("torch.save(payload, MODELS_ROOT / 'best.pt')", sources)
        self.assertIn("'talc_pixels_ignored': False", sources)
        self.assertIn("'ignore_pixels_ignored': True", sources)
        self.assertIn("reviewed talc pixels have target class `2`", sources.lower())
        self.assertIn("weights=weight", sources)
        self.assertIn("def resize_cache_spatial", sources)
        self.assertIn("source_train_cache = resize_cache_spatial", sources)
        self.assertIn("test_cache = resize_cache_spatial", sources)
        self.assertIn("multiclass_weighted_dice_loss_from_logits", sources)
        self.assertIn("balanced_class_weights_from_counts", sources)
        self.assertIn("class_weights_from_cache", sources)
        self.assertIn("class_weighted_cross_entropy", sources)
        self.assertIn("class_weighted_dice", sources)
        self.assertIn("F.cross_entropy(logits, target.long(), weight=resolved_class_weights, reduction='none')", sources)
        self.assertIn("class_weights=resolved_class_weights", sources)
        self.assertIn("prediction_diagnostics", sources)
        self.assertIn("selection_score_from_metrics", sources)
        self.assertIn("selection_score", sources)
        self.assertIn("0.4 * active_talc_iou + 0.4 * active_ore_iou + 0.2 * source_ore_iou", sources)
        self.assertIn("active_diagnostics", sources)
        self.assertIn("active_diagnostics['talc_pred_pixels'] == 0", sources)
        self.assertIn("best.pt will not be updated until talc_pred_pixels > 0", sources)
        self.assertIn("active_diagnostics['talc_pred_pixels'] > 0", sources)
        self.assertIn("selection_score is not None and talc_prediction_ok and selection_score > best_selection_score", sources)
        self.assertIn("'requires_active_talc_pred_pixels_gt_zero': True", sources)
        self.assertIn("binarize_masks=False", sources)
        self.assertIn("No talc pixels found in the train cache", sources)
        self.assertIn("TRAIN_ON_SOURCE_TEST = False", sources)
        self.assertIn("LOAD_BASE_CHECKPOINT = True", sources)


if __name__ == "__main__":
    unittest.main()
